name: Python Application CI

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the OS for the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Pull the repository's code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover  # Discover and run tests
